apiVersion: v1
kind: ReplicationController
metadata:
  name: server-letsencryptor
spec:
  replicas: 1
  selector:
    name: server-letsencryptor
  template:
    metadata:
      labels:
        name: server-letsencryptor
      name: server-letsencryptor
    spec:
      containers:
      - imagePullPolicy: Always
        image: gcr.io/test-cg/server-letsencryptor:2016-04-15T11-31-09Z
        name: server-letsencryptor
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: letsencryptor-workdir
        - mountPath: /var/lib/letsencrypt
          name: letsencryptor-config
      volumes:
        # This GCE PD must already exist. Read README for more information
      - name: letsencryptor-workdir
        gcePersistentDisk:
          pdName: server-letsencryptor-workdir
          fsType: ext4
      - name: letsencryptor-config
        gcePersistentDisk:
          pdName: server-letsencryptor-config
          fsType: ext4
